# Starter pipeline
pool:
  vmImage: 'Ubuntu 16.04'
   
steps:
- task: riezebosch.Packer.PackerTool.PackerTool@0
  displayName: 'Use Packer 1.3.2'
  inputs:
    version: 1.3.2

- task: Packer@1
  displayName: 'packer validate'
  inputs:
    connectedServiceType: azure
    connectedServiceAzure: 'packer-infra4711'
    templatePath: ubuntu1804.json
    #force: true|false Force a build to continue if artifacts exist, deletes existing artifacts
    variables: |+
        resource_group=$(resource-group)
        storage_account=$(storage-account)
    #variables-file: JSON file containing user variables.
    #options: Additional options, see Packer Commands (CLI)  for more information.
    command: validate

- task: Packer@1
  displayName: 'packer build'
  inputs:
    connectedServiceType: azure
    connectedServiceAzure: 'packer-infra4711'
    templatePath: ubuntu1804.json
    #force: true|false Force a build to continue if artifacts exist, deletes existing artifacts
    variables: |+
        resource_group=$(resource-group)
        storage_account=$(storage-account)
    #variables-file: JSON file containing user variables.
    #options: Additional options, see Packer Commands (CLI)  for more information.
    command: build